package Question;


import Result.Result_Activity;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import Menu.Menu;
import User.*;
import Menu.*;
import Question.*;
import Result.*;
import History.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author killua
 */

//inheritance
public class Question_Activity extends javax.swing.JFrame {
boolean empty;
int array=0;
int score=0;
public static String result = "Default";
ButtonGroup g = new ButtonGroup();
Question q = new Question();
    /**
     * Creates new form Question_Activity
     */
    public Question_Activity() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    
    //method score();
    void score(){
         if(yes_rb.isSelected()){
            empty=false;
        }else if(no_rb.isSelected()){
            empty=false;
        }else{
            empty=true;
        }
        if(!(empty)){
            if(yes_rb.isSelected()){
                score += 1;
            }else if(no_rb.isSelected()){

            }
            g.clearSelection();
            empty=false;
            array++;
            if(array<q.Questions.length){
                question_label.setText(q.Questions[array]);
            }else{
                if(User_Activity.VACCINE == "-"){
                if(score<7){
                  result = "Rendah";
                }else if(score<14){
                    result = "Sedang";
                }else{
                    result = "Tinggi";
                }
                }else if(User_Activity.VACCINE == "Vaccine 1"){
                if(score<8){
                  result = "Rendah";
                }else if(score<15){
                    result = "Sedang";
                }else{
                    result = "Tinggi";
                }
                }else if(User_Activity.VACCINE == "Vaccine 2"){
                if(score<9){
                  result = "Rendah";
                }else if(score<16){
                    result = "Sedang";
                }else{
                    result = "Tinggi";
                }
                }else if(User_Activity.VACCINE == "Vaccine Booster"){
                if(score<10){
                  result = "Rendah";
                }else if(score<17){
                    result = "Sedang";
                }else{
                    result = "Tinggi";
                }
                }
                JOptionPane.showMessageDialog(this,"Survey Finished!");
                User_Activity.user.setResult(result);
                User_Activity.user.result_arr.add(result);
                Result_Activity r = new Result_Activity();
                r.setVisible(true);
                this.setVisible(false);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Input your option!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        yes_rb = new javax.swing.JRadioButton();
        question_label = new javax.swing.JLabel();
        no_rb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        next_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(83, 73, 189));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(143, 100, 226));

        yes_rb.setFont(new java.awt.Font("sansserif", 0, 38)); // NOI18N
        yes_rb.setText("Yes");
        yes_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_rbActionPerformed(evt);
            }
        });

        question_label.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        question_label.setText("Saya tidak memakai masker pada saat berkumpul dengan orang lain");
        question_label.setToolTipText("");
        question_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        question_label.setMaximumSize(new java.awt.Dimension(610, 92));
        question_label.setMinimumSize(new java.awt.Dimension(610, 92));
        question_label.setPreferredSize(new java.awt.Dimension(610, 92));

        no_rb.setFont(new java.awt.Font("sansserif", 0, 38)); // NOI18N
        no_rb.setText("No");
        no_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_rbActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/image 5.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_rb)
                    .addComponent(yes_rb)
                    .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes_rb)
                .addGap(18, 18, 18)
                .addComponent(no_rb)
                .addGap(106, 106, 106))
        );

        jPanel1.setBackground(new java.awt.Color(83, 73, 189));

        next_button.setBackground(new java.awt.Color(56, 211, 202));
        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NEXT -_.png"))); // NOI18N
        next_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        next_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_buttonMouseClicked(evt);
            }
        });
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next_button)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next_button)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
            if(array<q.Questions.length){
            question_label.setText(q.Questions[array]);
            }else{
            }
        g.add(yes_rb);
        g.add(no_rb);
    }//GEN-LAST:event_formWindowActivated

    private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed
        // TODO add your handling code here:
        //call score() method;
        score();
    }//GEN-LAST:event_next_buttonActionPerformed

    private void next_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_next_buttonMouseClicked

    private void no_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_rbActionPerformed

    private void yes_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yes_rbActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //polymorphism
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton next_button;
    private javax.swing.JRadioButton no_rb;
    private javax.swing.JLabel question_label;
    private javax.swing.JRadioButton yes_rb;
    // End of variables declaration//GEN-END:variables
}
